name: Node.js CI

env:
    OUTPUT_PATH: ${{ github.workspace }}

on:
    push:
        branches:
            - master
        paths:
            - '.github/workflows/nodejs_ci.yml'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Cache Node.js dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('${{ env.OUTPUT_PATH }}/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 'latest'
